### ISSUE TITLE
run error need help

### ISSUE THREAD

**Issue by lotey** [Xu-Mj/sandcat-backend#12]
run error with minio,here is log msg
![image](https://github.com/Xu-Mj/sandcat-backend/assets/19348658/a19160be-8f7c-45de-a41d-ab0d3b6f1b30)

**Comment by Xu-Mj** [comment]
check the minio status in Docker, make sure it is running.

**Comment by lotey** [comment]
minio run ok,this url http://xmj.minio:9000 can't visit
![image](https://github.com/Xu-Mj/sandcat-backend/assets/19348658/967b24e6-0912-4cc8-9abd-e29fbbc9b3da)

**Comment by lotey** [comment]
I already create manually xmj bucket with web url，but not run ok

**Comment by Xu-Mj** [comment]
if you want to access the minio management site, try this `http://172.18.0.4:33103`. there is no need to manually create buckets. I'm uncertain about the specific issue that caused the error you encountered. could you send the image or file in `sandcat` frontend?

**Comment by lotey** [comment]
i try again with no docker run ok,maybe docker config has error,i'll see later

**Comment by lotey** [comment]
ok,very thanks，i'll continue to test
