### ISSUE TITLE
Add native suport？

### ISSUE THREAD

**Issue by zuiyu1998** [Xu-Mj/sandcat-backend#20]

**Comment by Xu-Mj** [comment]
Could you provide more specific details regarding the `native support` you're requesting?

**Comment by zuiyu1998** [comment]
现在使用websocket协议用于接入层。或许可以添加socket支持。

**Comment by Xu-Mj** [comment]
currently the client side is build with rust wasm, and I'm not sure whether wasm support the socket directly. we might support it in the future.
